version: 1.0.{build}

nuget:
  account_feed: false
  project_feed: false
  disable_publish_on_pr: true

branches:
  only:
  - master

image: Visual Studio 2017

init:
  - git config --global core.autocrlf input

configuration: Release

before_build:
  - cmd: msbuild /t:Restore src\CSemVer.Build.Tasks.sln

build:
  project: src\CSemVer.Build.Tasks.sln
  verbosity: minimal

artifacts:
  - path: BuildOutput\NuGet\*.nupkg
