name: CI-Build
on:
  push:
    branches:
      - develop

    paths-ignore:
      - '**.md'
      - '**.dic'

  pull_request:
    branches:
      - develop

    paths-ignore:
      - '**.md'
      - '**.dic'
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
           persist-credentials: false
           fetch-depth: 0

      - name: Build Source
        run: ./Build-All.ps1 -ForceClean -BuildMode Source

      - name: Publish build logs
        if: always() && github.event_name == 'pull_request'
        uses: actions/upload-artifact@v4
        with:
            name: Build Logs
            path: ./BuildOutput/BinLogs

      - name: Publish NuGET Packages
        uses: actions/upload-artifact@v4
        with:
            name: Nuget Packages
            path: ./BuildOutput/NuGet

