name: CI-Build
defaults:
    run:
        shell: pwsh

on:
  push:
    branches:
      - develop

    paths-ignore:
      - '**.md'
      - '**.dic'

  pull_request:
    branches:
      - develop

    paths-ignore:
      - '**.md'
      - '**.dic'

jobs:
  build_target:
    runs-on: windows-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
           persist-credentials: false
           fetch-depth: 0

      - name: Build Source
        run: ./Build-All.ps1 -ForceClean

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action/windows@v2
        with:
          files: BuildOutput/Test-Results/*.trx

      - name: Upload NuGET Packages
        uses: actions/upload-artifact@v4
        with:
            name: Nuget Packages
            path: ./BuildOutput/NuGet

