name: Release-Build
on:
  push:
    tags:
        - 'v*'

jobs:
  release-build:
    runs-on: windows-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Build Source
        run: dotnet build src/CSemVer.Build.Tasks.sln

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: true
          prerelease: false

      - name: Publish packages to NuGet.org
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.nugetpush_access_token }}
          DOTNET_CLI_TELEMETRY_OPTOUT: 1
        run: |
            dir .\BuildOutput\NuGet\*.nupkg | %{dotnet nuget push $_ -k $env:NUGET_AUTH_TOKEN -s 'https://api.nuget.org/v3/index.json' -n true}
